### ISSUE TITLE
Readme. Parse AST back to JSX

### ISSUE THREAD

**Issue by Seanmclem** [acornjs/acorn-jsx#121]
The readme mentions parsing JSX to an AST, but can it parse AST back to JSX? 

Is there additional documentation anywhere? The readme is pretty sparse.

**Comment by Adam-Collier** [comment]
@Seanmclem did you find a way to do this? I'm looking to do this myself

**Comment by Seanmclem** [comment]
> @Seanmclem did you find a way to do this? I'm looking to do this myself

I ended up using babel to parse. I'm add some code samples momentarily

**Comment by neoncube2** [comment]
I'm also interested in this :)

**Comment by neoncube2** [comment]
It turns out that this was as easy as using [astring-jsx](https://www.npmjs.com/package/astring-jsx):

```js
const astring = require('astring-jsx');

const ast = acorn.parse('<JS code here>')

const generatedCode = astring.generate(ast);
```

(It looks like [@barelyhuman/astring-jsx](https://github.com/barelyhuman/astring-jsx) is a maintained fork of `astring-jsx`)

Thanks to https://github.com/acornjs/acorn/issues/519#issuecomment-2599679104 for pointing me in the right direction! :)
